Repository Shah-Kush/TellMeAStory4, pull requests merged in 2022-04, with the labels that each got.

#56 Merge feature/story-creation into develop
  story/tellmeastory/forms.py
  story/tellmeastory/migrations/0002_node.py
  story/tellmeastory/models.py
  story/tellmeastory/templates/tellmeastory/make_node.html
  story/tellmeastory/tests/test_models.py
  story/tellmeastory/tests/test_nodecreation.py
  story/tellmeastory/urls.py
  story/tellmeastory/views.py
Labels: enhancement

#57 Feature/image on node
  .idea/shelf/Uncommitted_changes_before_Update_at_3_27_22,_9_33_PM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_3_27_22__9_33_PM__Changes_.xml
  .idea/workspace.xml
  requirements.txt
  story/media/storyimages/test_image.jpeg
  story/media/storyimages/test_image_4a7gmiP.jpeg
  story/media/storyimages/test_image_7ozrQGA.jpeg
  story/media/storyimages/test_image_sQMrghW.jpeg
  story/story/settings.py
  story/tellmeastory/admin.py
  story/tellmeastory/forms.py
  story/tellmeastory/migrations/0002_node.py
  story/tellmeastory/migrations/0003_remove_node_has_image_file.py
  story/tellmeastory/migrations/0004_node_has_image_file.py
  story/tellmeastory/migrations/0005_alter_node_image.py
  story/tellmeastory/migrations/0006_alter_node_image.py
  story/tellmeastory/migrations/0007_alter_node_image.py
  story/tellmeastory/migrations/0008_remove_node_image.py
  story/tellmeastory/migrations/0009_node_image.py
  story/tellmeastory/migrations/0010_alter_node_image.py
  story/tellmeastory/migrations/0011_alter_node_image.py
  story/tellmeastory/migrations/0012_alter_node_node_author.py
  story/tellmeastory/models.py
  story/tellmeastory/templates/tellmeastory/account.html
  story/tellmeastory/templates/tellmeastory/addnodeimage.html
  story/tellmeastory/tests/test_imageOnNode.py
  story/tellmeastory/urls.py
  story/tellmeastory/views.py
Labels: enhancement

#58 Feature/attach tags to node
  story/managetags/models.py
  story/media/storyimages/test_image_9yVYXk0.jpeg
  story/media/storyimages/test_image_L8u2rG3.jpeg
  story/media/storyimages/test_image_eKAUwcP.jpeg
  story/tellmeastory/migrations/0001_initial.py
  story/tellmeastory/migrations/0002_node.py
  story/tellmeastory/migrations/0003_remove_node_has_image_file.py
  story/tellmeastory/migrations/0004_node_has_image_file.py
  story/tellmeastory/migrations/0005_alter_node_image.py
  story/tellmeastory/migrations/0006_alter_node_image.py
  story/tellmeastory/migrations/0007_alter_node_image.py
  story/tellmeastory/migrations/0008_remove_node_image.py
  story/tellmeastory/migrations/0009_node_image.py
  story/tellmeastory/migrations/0010_alter_node_image.py
  story/tellmeastory/migrations/0011_alter_node_image.py
  story/tellmeastory/migrations/0012_alter_node_node_author.py
  story/tellmeastory/models.py
  story/tellmeastory/tests/test_attachTag.py
Labels: enhancement

#59 Feature/maturity label
  story/media/storyimages/test_image.jpeg
  story/media/storyimages/test_image_4a7gmiP.jpeg
  story/media/storyimages/test_image_7ozrQGA.jpeg
  story/media/storyimages/test_image_9yVYXk0.jpeg
  story/media/storyimages/test_image_L8u2rG3.jpeg
  story/media/storyimages/test_image_eKAUwcP.jpeg
  story/media/storyimages/test_image_sQMrghW.jpeg
  story/tellmeastory/forms.py
  story/tellmeastory/migrations/0002_user_mature.py
  story/tellmeastory/models.py
  story/tellmeastory/tests/test_attachTag.py
  story/tellmeastory/tests/test_models.py
  story/tellmeastory/views.py
Labels: enhancement

#61 Bug/add image node validation
  story/tellmeastory/tests/test_imageOnNode.py
  story/tellmeastory/views.py
Labels: bug

#65 added testing notes
  README.md
Labels: documentation, enhancement

#66 Release 2
  .idea/shelf/Uncommitted_changes_before_Update_at_3_27_22,_9_33_PM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_3_27_22__9_33_PM__Changes_.xml
  .idea/workspace.xml
  README.md
  requirements.txt
  story/managetags/models.py
  story/media/storyimages/test_image.jpeg
  story/story/settings.py
  story/tellmeastory/admin.py
  story/tellmeastory/forms.py
  story/tellmeastory/migrations/0001_initial.py
  story/tellmeastory/migrations/0002_user_mature.py
  story/tellmeastory/models.py
  story/tellmeastory/templates/tellmeastory/account.html
  story/tellmeastory/templates/tellmeastory/addnodeimage.html
  story/tellmeastory/templates/tellmeastory/make_node.html
  story/tellmeastory/templates/tellmeastory/profile.html
  story/tellmeastory/templates/tellmeastory/profileNotFound.html
  story/tellmeastory/tests/test_attachTag.py
  story/tellmeastory/tests/test_imageOnNode.py
  story/tellmeastory/tests/test_models.py
  story/tellmeastory/tests/test_nodecreation.py
  story/tellmeastory/tests/test_profile.py
  story/tellmeastory/urls.py
  story/tellmeastory/views.py
Labels: documentation, enhancement

#81 Added no tags exist check and fixed image posting
  story/tellmeastory/models.py
  story/tellmeastory/tests/test_integrated_nodecreation.py
  story/tellmeastory/views.py
Labels: bug

#83 Update readme for iteration 3
  README.md
Labels: documentation
